// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datacustomer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32
	Username  string
	Password  string
	FullName  string
	Email     string
	CreatedOn pgtype.Timestamp
	LastLogin pgtype.Timestamp
}

type Address struct {
	ID            int32
	AccountID     int32
	Address1      string
	Address2      pgtype.Text
	City          string
	StateID       int32
	ZipCode       int16
	RecipientName string
	AddedOn       pgtype.Timestamp
}

type AddressState struct {
	ID   int32
	Name string
}
