// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package datawarehouse

import (
	"context"
)

type Querier interface {
	CreateWarehouse(ctx context.Context, name string) error
	DeleteAllWarehouses(ctx context.Context) error
	GetWarehouses(ctx context.Context) ([]Warehouse, error)
}

var _ Querier = (*Queries)(nil)
