// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package customer

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32
	Username  string
	Password  string
	FullName  string
	Email     string
	CreatedOn time.Time
	LastLogin sql.NullTime
}

type Address struct {
	ID            int32
	AccountID     int32
	Address1      string
	Address2      sql.NullString
	City          string
	StateID       int32
	ZipCode       int16
	RecipientName string
	AddedOn       time.Time
}

type AddressState struct {
	ID   int32
	Name string
}
